services:

  backend:
    build: ./backend

    ports:
      - "8000:8000"

    volumes:
      - ./backend:/app

    depends_on:
      - redis
      - postgres

    command: python manage.py runserver 0.0.0.0:8000

  redis:
    image: redis:7-alpine

    ports:
      - "6380:6379"

  postgres:
   image: postgres:17

   container_name: pricepulse-postgres

   restart: always

   environment:
     POSTGRES_DB: pricepulse
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: postgres

   ports:
     - "5432:5432"

   volumes:
     - postgres_data:/var/lib/postgresql/data

  celery:
      build:
        context: ./backend
        dockerfile: Dockerfile

      container_name: pricepulse-celery

      command: celery -A config worker --loglevel=info

      volumes:
       - ./backend:/app

      depends_on:
      - redis

  celery-beat:
     build:
      context: ./backend
      dockerfile: Dockerfile

     command: celery -A config beat --loglevel=info

     volumes:
      - ./backend:/app

     depends_on:
      - redis
      - celery
  
volumes:
    postgres_data: