# Generated by Django 6.0.7 on 2026-07-10 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_remove_product_image_url_category_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('logo', models.URLField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('in_stock', models.BooleanField(default=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_history', to='catalog.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_history', to='pricing.store')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['product', '-recorded_at'], name='pricing_pri_product_2a5603_idx'), models.Index(fields=['store', '-recorded_at'], name='pricing_pri_store_i_f5f197_idx')],
            },
        ),
        migrations.CreateModel(
            name='CurrentPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('in_stock', models.BooleanField(default=True)),
                ('product_url', models.URLField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='current_prices', to='catalog.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='current_prices', to='pricing.store')),
            ],
            options={
                'ordering': ['product__name', 'store__name'],
                'indexes': [models.Index(fields=['product'], name='pricing_cur_product_8fa28c_idx'), models.Index(fields=['store'], name='pricing_cur_store_i_f8861e_idx')],
                'constraints': [models.UniqueConstraint(fields=('product', 'store'), name='unique_product_store')],
            },
        ),
    ]
