# Generated by Django 6.0.7 on 2026-07-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_rename_catalog_pro_name_f8bd91_idx_catalog_pro_name_f603c0_idx'),
        ('pricing', '0002_currentprice_mrp_eta'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='currentprice',
            index=models.Index(fields=['product', 'price'], name='pricing_cur_product_7b26f8_idx'),
        ),
        migrations.AddIndex(
            model_name='currentprice',
            index=models.Index(fields=['product', '-last_updated'], name='pricing_cur_product_c4bede_idx'),
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['product', 'store', '-recorded_at'], name='pricing_pri_product_85bb94_idx'),
        ),
    ]
