# Generated by Django 6.0.7 on 2026-07-16 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_image_url_and_name_index'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='catalog_pro_name_f603c0_idx',
            old_name='catalog_pro_name_f8bd91_idx',
        ),
    ]
